services:
  app-backend:
    build: ./app-backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://${POSTGRES_IP}:5432/${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  app-web-frontend:
    build:
      context: ./app-web-frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:443"
      - "80:80"
    depends_on:
      - app-backend

  db:
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
