spring:
  application:
    name: app-backend
  liquibase:
    change-log: classpath:db/changelog.yaml
  jwt:
    secret: 8elRtZWIZ0586hYwwzy+Mqtvp3GjkvaTo0oFJiaTPHwJEn66sO9VpH6nCW+2r/kw/ua9U5ZpJIUUeqnjHsyE9Q==

openai:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: key

recommendation:
  doctor: "Formulate a recommendation for a psychologist on a patient who describes his condition as follows:\n"
  literature: "Recommend literature and podcasts on the following topic: "