name: CI Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Make the deploy.sh script executable
      - name: Make deploy script executable
        run: chmod +x ./deploy.sh

      # Step 4: Run the deploy.sh script
      - name: Run deploy script
        run: ./deploy.sh

      # Step 5: Ensure all containers are running (Optional, only if you want to check this)
      - name: Ensure containers are running
        run: docker-compose ps

      # Step 6: Clean up after the build (Optional)
      - name: Clean up
        if: always()  # This step will run even if earlier steps fail
        run: docker-compose down
