name: Test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradlew
        run: chmod +x ./gradlew
        working-directory: ./app-backend

      - name: Build
        run: ./gradlew build -x test
        working-directory: ./app-backend

      - name: Run Test
        run: ./gradlew test
        working-directory: ./app-backend