name: Deploy Script

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Running deploy.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Run Deploy Script
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh